version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: voting_db
    environment:
      POSTGRES_DB: Votaciones_Blockchain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nicolas123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./SW2-grupal-backend
      dockerfile: Dockerfile
    container_name: voting_backend
    env_file:
      - ./SW2-grupal-backend/.env
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./SW2-grupal-frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=/api
    container_name: voting_frontend
    restart: unless-stopped
    depends_on:
      - backend

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - '80:80'    # Tráfico HTTP público (redirecciona a HTTPS)
      - '81:81'    # Panel de administración visual de NPM
      - '443:443'  # Tráfico HTTPS público
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

volumes:
  pgdata:
  npm_data:
  npm_letsencrypt:
