sonar.projectKey=backend-api
sonar.projectName=Backend NestJS (Votacion)
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=**/*.spec.ts, **/migrations/**
sonar.host.url=http://localhost:9000
sonar.login=sqp_6a01aeb0ab5b3b0e2bf12a4fb72066531c302ff7