sonar.projectKey=frontend-react
sonar.projectName=Frontend React (Votacion)
sonar.sources=src
sonar.exclusions=**/*.test.js, **/*.spec.js, **/node_modules/**, **/dist/**
sonar.host.url=http://localhost:9000
sonar.login=sqp_7efa02ead535945c6921c8947b74e1c677472385